### ISSUE TITLE
Move the project to a new clean repository

### ISSUE THREAD

**Issue by D4no0** [JeromeDeBretagne/erlanglauncher#3]
I would suggest to clean up the project, add commentaries and move it to another clean repository. This way we can track easier what work is required to get it going.

**Comment by JeromeDeBretagne** [comment]
Hi @D4no0,

I've made this repository compatible with Android 11, independant of the actual application package name and it now even works for multiple Android users. I'm not sure how much more clean-up would be valuable. 

For me, this is a simple sample code showing that it is possible to install an Erlang/OTP runtime and to run some Erlang code on Android; and it presents one possible way to achieve this.

Feel free to re-open this issue if you have more concrete requests.
