### ISSUE TITLE
Different way to copy binaries than mapping to .so files

### ISSUE THREAD

**Issue by D4no0** [JeromeDeBretagne/erlanglauncher#6]
I saw that termux used the same method to pass binaries as native libraries, however this seems very hacky. I investigated for some time alternatives and noticed that someone mentioned putting binary in /libs folder in the termux issue discussion however it doesn't seem to work. My fear is that in next updates they will check the .so files to ensure they are really shared objects and then this approach will not work anymore. Any thoughts on this, maybe you found something interesting I missed?

**Comment by JeromeDeBretagne** [comment]
I haven't found any other solution so far, no.

Executable binaries and shared objects are very similar technically, both using the ELF format, so I'm not sure that Google will get any real benefits to tighten up even more what's allowed in the jniLibs directories, especially as they are already read-only (which is very robust). 

Who knows how this could change in a future Android release. If at one point they add some newer restrictions, the new limitations will have to be investigated at that time but nothing that we can do for the moment.

**Comment by D4no0** [comment]
I have a feeling that Android is doing best effort to make it hard for other platforms to work out of the box, otherwise I wouldn't see why no official way and documentation is provided on how to copy prebuilt projects. I also noticed that when hosting phoenix server, the connection was throttled very hard, I cannot confirm however if this was software or hardware issue.
